import type { EndpointPreset } from "@/types/api";

/**
 * Presets for real backend endpoints only, taken from the actual controllers
 * under apps/backend. Path placeholders like {projectId} must be replaced
 * before sending. Nothing is executed automatically.
 */
export const ENDPOINT_PRESETS: EndpointPreset[] = [
  // --- Health ---
  {
    id: "health",
    group: "Health",
    name: "Backend health",
    method: "GET",
    path: "/actuator/health",
    description: "Actuator health probe.",
    authRequired: false,
  },

  // --- Auth ---
  {
    id: "auth-register-admin",
    group: "Auth",
    name: "Register organization admin",
    method: "POST",
    path: "/auth/register-admin",
    body: JSON.stringify(
      {
        name: "Demo Admin",
        email: "admin@example.com",
        password: "Password123!",
        organizationName: "Demo Organization",
        headquarterAddress: "Demo Street 1",
      },
      null,
      2,
    ),
    description: "Creates an organization plus its first admin.",
    authRequired: false,
  },
  {
    id: "auth-login",
    group: "Auth",
    name: "Login",
    method: "POST",
    path: "/auth/login",
    body: JSON.stringify(
      { email: "admin@example.com", password: "Password123!" },
      null,
      2,
    ),
    description: "Returns an access/refresh token pair.",
    authRequired: false,
  },
  {
    id: "auth-refresh",
    group: "Auth",
    name: "Refresh tokens",
    method: "POST",
    path: "/auth/refresh",
    body: JSON.stringify({ refreshToken: "<paste-refresh-token>" }, null, 2),
    description: "Rotates the refresh token and issues a new pair.",
    authRequired: false,
  },
  {
    id: "auth-me",
    group: "Auth",
    name: "Current user",
    method: "GET",
    path: "/auth/me",
    description: "The authenticated user's profile and roles.",
    authRequired: true,
  },
  {
    id: "auth-sessions",
    group: "Auth",
    name: "List sessions",
    method: "GET",
    path: "/auth/sessions",
    description: "Active refresh sessions of the current user.",
    authRequired: true,
  },
  {
    id: "auth-logout",
    group: "Auth",
    name: "Logout (current session)",
    method: "POST",
    path: "/auth/logout",
    description: "Ends the current session.",
    authRequired: true,
  },

  // --- Organization / Departments ---
  {
    id: "org-invite",
    group: "Organization",
    name: "Employee invite link",
    method: "GET",
    path: "/organizations/current/invite",
    description: "Invite URL for registering employees.",
    authRequired: true,
    role: "ORGANIZATION_ADMIN",
  },
  {
    id: "departments-create",
    group: "Organization",
    name: "Create department",
    method: "POST",
    path: "/departments",
    body: JSON.stringify({ name: "Engineering" }, null, 2),
    description: "Creates a department.",
    authRequired: true,
    role: "ORGANIZATION_ADMIN",
  },
  {
    id: "departments-list",
    group: "Organization",
    name: "List departments",
    method: "GET",
    path: "/departments",
    description: "All departments of the organization.",
    authRequired: true,
  },
  {
    id: "departments-assign-manager",
    group: "Organization",
    name: "Assign department manager",
    method: "PUT",
    path: "/departments/{departmentId}/manager",
    body: JSON.stringify({ userId: "{userId}" }, null, 2),
    description: "Assigns a DEPARTMENT_MANAGER user to the department.",
    authRequired: true,
    role: "ORGANIZATION_ADMIN",
  },
  {
    id: "departments-add-member",
    group: "Organization",
    name: "Add department member",
    method: "POST",
    path: "/departments/{departmentId}/members/{userId}",
    description: "Adds an employee to the managed department.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },
  {
    id: "users-list",
    group: "Organization",
    name: "List users",
    method: "GET",
    path: "/users",
    description: "Organization users.",
    authRequired: true,
    role: "ORGANIZATION_ADMIN",
  },
  {
    id: "users-roles",
    group: "Organization",
    name: "Update user roles",
    method: "PATCH",
    path: "/users/{userId}/roles",
    body: JSON.stringify(
      { roles: ["EMPLOYEE", "PROJECT_MANAGER"] },
      null,
      2,
    ),
    description: "Grants access roles (EMPLOYEE is always kept).",
    authRequired: true,
    role: "ORGANIZATION_ADMIN",
  },
  {
    id: "team-roles-create",
    group: "Organization",
    name: "Create team role",
    method: "POST",
    path: "/team-roles",
    body: JSON.stringify(
      { name: "Backend Developer", description: "Builds services" },
      null,
      2,
    ),
    description: "Creates an informative project team role.",
    authRequired: true,
    role: "ORGANIZATION_ADMIN",
  },
  {
    id: "team-roles-list",
    group: "Organization",
    name: "List team roles",
    method: "GET",
    path: "/team-roles",
    description: "Team roles of the organization.",
    authRequired: true,
  },

  // --- Skills ---
  {
    id: "skill-categories-create",
    group: "Skills",
    name: "Create skill category",
    method: "POST",
    path: "/skill-categories",
    body: JSON.stringify({ name: "Programming Language" }, null, 2),
    description: "Creates a skill category.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },
  {
    id: "skills-create",
    group: "Skills",
    name: "Create skill",
    method: "POST",
    path: "/skills",
    body: JSON.stringify(
      { categoryId: "{categoryId}", name: "Java" },
      null,
      2,
    ),
    description: "Creates a catalog skill in a category.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },
  {
    id: "skills-list",
    group: "Skills",
    name: "List skills",
    method: "GET",
    path: "/skills",
    description: "Skill catalog of the organization.",
    authRequired: true,
  },

  // --- Employee expertise ---
  {
    id: "me-skills-list",
    group: "Employee expertise",
    name: "My skills",
    method: "GET",
    path: "/me/skills",
    description: "The authenticated user's skill profile.",
    authRequired: true,
    role: "EMPLOYEE",
  },
  {
    id: "me-skills-assign",
    group: "Employee expertise",
    name: "Self-assign skill",
    method: "POST",
    path: "/me/skills",
    body: JSON.stringify(
      {
        skillId: "{skillId}",
        level: "DOES",
        experience: "ONE_TO_TWO_YEARS",
      },
      null,
      2,
    ),
    description: "Adds a catalog skill to the own profile.",
    authRequired: true,
    role: "EMPLOYEE",
  },

  // --- Projects (PM) ---
  {
    id: "projects-create",
    group: "Projects",
    name: "Create project",
    method: "POST",
    path: "/projects",
    body: JSON.stringify(
      {
        name: "Apollo",
        period: "FIXED",
        startDate: "2026-08-01",
        deadlineDate: "2026-12-31",
        status: "STARTING",
        generalDescription: "Demo project",
        technologyStack: ["Java", "PostgreSQL"],
        teamRoles: [{ teamRoleId: "{teamRoleId}", requiredMembers: 1 }],
      },
      null,
      2,
    ),
    description: "Creates a project owned by the caller.",
    authRequired: true,
    role: "PROJECT_MANAGER",
  },
  {
    id: "projects-managed",
    group: "Projects",
    name: "My managed projects",
    method: "GET",
    path: "/projects/managed",
    description: "Projects owned by the authenticated PM.",
    authRequired: true,
    role: "PROJECT_MANAGER",
  },
  {
    id: "projects-get",
    group: "Projects",
    name: "Get owned project",
    method: "GET",
    path: "/projects/{projectId}",
    description: "Owner-scoped project read.",
    authRequired: true,
    role: "PROJECT_MANAGER",
  },
  {
    id: "projects-patch-status",
    group: "Projects",
    name: "Change project status",
    method: "PATCH",
    path: "/projects/{projectId}",
    body: JSON.stringify({ status: "IN_PROGRESS" }, null, 2),
    description: "Partial project update (status shown as example).",
    authRequired: true,
    role: "PROJECT_MANAGER",
  },

  // --- Project views ---
  {
    id: "project-details",
    group: "Project views",
    name: "Project details",
    method: "GET",
    path: "/projects/{projectId}/details",
    description: "Detail page for users related to the project.",
    authRequired: true,
  },
  {
    id: "project-team",
    group: "Project views",
    name: "Project team view",
    method: "GET",
    path: "/projects/{projectId}/team",
    description: "Proposed, active, and past team members.",
    authRequired: true,
  },
  {
    id: "me-projects",
    group: "Project views",
    name: "My project history",
    method: "GET",
    path: "/me/projects",
    description: "Own current and past allocation episodes.",
    authRequired: true,
    role: "EMPLOYEE",
  },
  {
    id: "department-projects",
    group: "Project views",
    name: "Department portfolio",
    method: "GET",
    path: "/department/projects",
    description: "Projects with active managed-department members.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },

  // --- Team Finder ---
  {
    id: "team-finder",
    group: "Team Finder",
    name: "Run Team Finder",
    method: "POST",
    path: "/projects/{projectId}/team-finder",
    body: JSON.stringify(
      {
        includePartiallyAvailable: true,
        includeCloseToFinish: false,
        includeUnavailable: false,
        limit: 50,
      },
      null,
      2,
    ),
    description: "Deterministic candidate ranking for the project.",
    authRequired: true,
    role: "PROJECT_MANAGER",
  },

  // --- Allocation workflow ---
  {
    id: "assignment-propose",
    group: "Allocation",
    name: "Create assignment proposal",
    method: "POST",
    path: "/projects/{projectId}/assignment-proposals",
    body: JSON.stringify(
      {
        employeeId: "{employeeId}",
        workHoursPerDay: 4,
        teamRoleIds: ["{teamRoleId}"],
        comments: "Strong candidate",
      },
      null,
      2,
    ),
    description: "Proposes an employee for the owned project.",
    authRequired: true,
    role: "PROJECT_MANAGER",
  },
  {
    id: "dm-queue",
    group: "Allocation",
    name: "DM review queue",
    method: "GET",
    path: "/department/project-proposals?status=PENDING",
    description: "Assignment + deallocation proposals for review.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },
  {
    id: "assignment-accept",
    group: "Allocation",
    name: "Accept assignment",
    method: "POST",
    path: "/department/project-proposals/assignments/{proposalId}/accept",
    description: "Approves the proposal and creates the allocation.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },
  {
    id: "assignment-reject",
    group: "Allocation",
    name: "Reject assignment",
    method: "POST",
    path: "/department/project-proposals/assignments/{proposalId}/reject",
    description: "Rejects the pending assignment proposal.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },
  {
    id: "deallocation-propose",
    group: "Allocation",
    name: "Create deallocation proposal",
    method: "POST",
    path: "/projects/{projectId}/allocations/{allocationId}/deallocation-proposals",
    body: JSON.stringify({ reason: "Phase completed" }, null, 2),
    description: "Proposes ending an active allocation.",
    authRequired: true,
    role: "PROJECT_MANAGER",
  },
  {
    id: "deallocation-accept",
    group: "Allocation",
    name: "Accept deallocation",
    method: "POST",
    path: "/department/project-proposals/deallocations/{proposalId}/accept",
    description: "Approves the deallocation and ends the allocation.",
    authRequired: true,
    role: "DEPARTMENT_MANAGER",
  },
];
