spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/potriv
    username: potriv
    password: potriv
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false

  mail:
    host: localhost
    port: 1025
