package me.aydgn.potriv.security.entity;

public enum SecurityAuditEventType {
    ORGANIZATION_ADMIN_REGISTERED,
    EMPLOYEE_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    TOKEN_REFRESHED,
    REFRESH_TOKEN_REUSE_DETECTED,
    LOGOUT,
    LOGOUT_ALL,
    SESSION_REVOKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    USER_STATUS_CHANGED,
    USER_ROLES_CHANGED,
    EMPLOYEE_INVITE_ROTATED
}
