package me.aydgn.potriv.security.entity;

public enum SecurityAuditEventType {
    ORGANIZATION_ADMIN_REGISTERED,
    EMPLOYEE_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    TOKEN_REFRESHED,
    REFRESH_TOKEN_REUSE_DETECTED,
    LOGOUT,
    LOGOUT_ALL,
    SESSION_REVOKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    USER_STATUS_CHANGED,
    USER_ROLES_CHANGED,
    /**
     * Retained for audit rows written before invitations became
     * per-recipient. Nothing emits it any more — there is no shared link
     * left to rotate — but the column stores the name, so removing the
     * constant would make old history fail to load.
     */
    EMPLOYEE_INVITE_ROTATED,
    EMPLOYEE_INVITE_ISSUED,
    EMPLOYEE_INVITE_REVOKED,
    ADMIN_ORGANIZATION_UPDATED,
    ADMIN_DEPARTMENT_CREATED,
    ADMIN_DEPARTMENT_UPDATED,
    ADMIN_DEPARTMENT_DELETE_BLOCKED,
    ADMIN_DEPARTMENT_DELETED,
    ADMIN_SKILL_CATEGORY_CREATED,
    ADMIN_SKILL_CATEGORY_UPDATED,
    ADMIN_SKILL_CREATED,
    ADMIN_SKILL_UPDATED,
    ADMIN_SKILL_DEACTIVATED,
    ADMIN_SKILL_REACTIVATED,
    ADMIN_SKILL_DEPARTMENT_LINK_ADDED,
    ADMIN_SKILL_DEPARTMENT_LINK_REMOVED,
    ADMIN_USER_PROFILE_UPDATED,
    ADMIN_USER_STATUS_CHANGED,
    ADMIN_USER_UNLOCKED,
    ADMIN_USER_ACTION_BLOCKED,
    ADMIN_USER_ROLE_GRANTED,
    ADMIN_USER_ROLE_REVOKED,
    ADMIN_USER_ROLE_ACTION_BLOCKED,
    SYSTEM_ADMIN_BOOTSTRAP_CREATED,
    SYSTEM_ADMIN_BOOTSTRAP_RECONCILED,
    ADMIN_INVITATION_REVOKED,
    ADMIN_INVITATION_REGENERATED,
    ADMIN_PROJECT_STATUS_CHANGED,
    ADMIN_PROJECT_DELETED,
    ADMIN_PROJECT_ACTION_BLOCKED
}
